---

- name: Configure important user consistently named cat
  hosts: web1
  become: True
  vars_files:
    - secret.yml
  tasks:
  - name: cat exists with UID 6000
    user: 
      name: "{{ username }}"
      password: "{{ pwhash }}"
      state: present

...