- name: Install Zabbix 7 LTS in Rocky 9
  hosts: web1
  become: true
  tasks:
         
   - name: Add repository
     yum:
       disable_gpg_check: yes
       pkg: https://repo.zabbix.com/zabbix/7.0/rocky/9/x86_64/zabbix-release-7.0-2.el9.noarch.rpm    
       state: present
       
       
   - name: ensure a list of packages installed
     yum:
       name: "{{ packages }}"

     vars:
       packages:
         - zabbix-server-mysql
         - zabbix-web-mysql
         - zabbix-apache-conf 
         - zabbix-sql-scripts 
         - zabbix-selinux-policy 
         - zabbix-agent
         - postgresql
         - postgresql-server
         
       state: present   

   - name: Init postgresql
     command:
       cmd: "postgresql-setup --initdb"    

   - name: postgresql enabled and running
     service:
        name: "{{ item }}"
        enabled: true
        state: started
     with_items:
        - postgresql
        - zabbix-server
        - zabbix-agent


     notify: 
     - restart apache
     - restart postgresql


   - name: FirewallD rules
     firewalld:
        permanent: yes
        immediate: yes
        service: "{{ item }}"
        state: enabled
     with_items:
       - http
       - https
       - postgresql
       - zabbix-server
       - zabbix-agent
       - syslog-tls
       - syslog
       - ssh
       - snmptrap
       - snmp
       - smtps
       - smtp-submission
       - smtp
     notify: 
       - reload firewalld
       - restart apache
       - restart postgresql

  handlers:
  - name: reload firewalld
    service: name=firewalld state=reloaded

  - name: restart apache
    service: name=httpd state=restarted

  - name: restart postgresql
    service: name=postgresql state=restarted

  - name: restart zabbix-server
    service: name=zabbix-server state=restarted

  - name: restart zabbix-agent
    service: name=zabbix-agent state=restarted

  - name: restart php-fpm
    service: name=php-fpm state=restarted

